# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 12:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.IntegerField(default=2018, validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(1960)]),
        ),
    ]
