# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 12:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_auto_20180331_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='title',
            name='status',
            field=models.CharField(choices=[('TOWATCH', 'To Watch'), ('WATCHING', 'Watching'), ('WATCHED', 'Watched')], default='TOWATCH', max_length=8),
        ),
    ]
